### ISSUE TITLE
Album Art getting bigger with different dimensions

### ISSUE THREAD

**Issue by shinobukid** [henryli17/DontShrinkMyAlbumArt#1]
some of my music has different aspect ratios than the normal 500x500 to 1000x1000 is there any way to fix this?

**Comment by henryli17** [comment]
I believe this was fixed in version 0.0.2.

**Comment by shinobukid** [comment]
no sadly it still gets bigger and covers the time

**Comment by shinobukid** [comment]
> I believe this was fixed in version 0.0.2.


no sadly it still gets bigger and covers the time

**Comment by henryli17** [comment]
Could you send a screenshot?

**Comment by shinobukid** [comment]
> Could you send a screenshot?

https://share.icloud.com/photos/04bYZRPj_qfjWgn1yLjSM5vfQ

**Comment by shinobukid** [comment]
> Could you send a screenshot?

hello ???

**Comment by henryli17** [comment]
I don't have a jailbroken device to test/debug but you can try this fix (not sure if it works though).

[xyz.henryli17.dontshrinkmyalbumart_0.0.3-beta_iphoneos-arm.zip](https://github.com/henryli17/DontShrinkMyAlbumArt/files/8454948/xyz.henryli17.dontshrinkmyalbumart_0.0.3-beta_iphoneos-arm.zip)

**Comment by shinobukid** [comment]
> I don't have a jailbroken device to test/debug but you can try this fix (not sure if it works though).
> 
> [xyz.henryli17.dontshrinkmyalbumart_0.0.3-beta_iphoneos-arm.zip](https://github.com/henryli17/DontShrinkMyAlbumArt/files/8454948/xyz.henryli17.dontshrinkmyalbumart_0.0.3-beta_iphoneos-arm.zip)

this fixed it thank you
